const ALIGNMENT_VILLAGE = "Village"
const ALIGNMENT_MAFIA = "Mafia"
const ALIGNMENT_INDEPENDENT = "Independent"
const ALIGNMENT_MONSTERS = "Monsters"

module.exports = {
    ALIGNMENT_VILLAGE,
    ALIGNMENT_MAFIA,
    ALIGNMENT_INDEPENDENT,
    ALIGNMENT_MONSTERS,
}
