ALIGNMENT_VILLAGE = "Village"
ALIGNMENT_MAFIA = "Mafia"
ALIGNMENT_INDEPENDENT = "Independent"
ALIGNMENT_MONSTERS = "Monsters"

module.exports = {
    ALIGNMENT_VILLAGE,
    ALIGNMENT_MAFIA,
    ALIGNMENT_INDEPENDENT,
    ALIGNMENT_MONSTERS,
}
