// night kill
DEATH_TYPE_BASIC = "basic"

DEATH_TYPE_LYNCH = "lynch"
DEATH_TYPE_LEAVE = "leave"
DEATH_TYPE_VEG = "veg"

DEATH_TYPE_GUN = "gun"
DEATH_TYPE_BOMB = "bomb"

DEATH_TYPE_LYNCH_REVENGE = "lynchRevenge"
DEATH_TYPE_BURN = "burn"
DEATH_TYPE_POISON = "poison"

module.exports = {
    DEATH_TYPE_BASIC,
    DEATH_TYPE_LYNCH,
    DEATH_TYPE_LEAVE,
    DEATH_TYPE_VEG,

    DEATH_TYPE_GUN,
    DEATH_TYPE_BOMB,

    DEATH_TYPE_LYNCH_REVENGE,
    DEATH_TYPE_BURN,
    DEATH_TYPE_POISON,
}