const HOT_SPRINGS_MEETING_PRIORITY = 1
const BANQUET_MEETING_PRIORITY = 2
const JAIL_MEETING_PRIORITY = 3

module.exports = {
    HOT_SPRINGS_MEETING_PRIORITY,
    BANQUET_MEETING_PRIORITY,
    JAIL_MEETING_PRIORITY,
}