const MEETING_PRIORITY_JAIL = 10
const MEETING_PRIORITY_BANQUET = 5
const MEETING_PRIORITY_HOT_SPRINGS = 1

module.exports = {
    MEETING_PRIORITY_JAIL,
    MEETING_PRIORITY_BANQUET,
    MEETING_PRIORITY_HOT_SPRINGS,
}