const MEETING_PRIORITY_LOCK = 20
const MEETING_PRIORITY_JAIL = 10
const MEETING_PRIORITY_SEANCE = 8
const MEETING_PRIORITY_BANQUET = 5
const MEETING_DEAD_PARTY = 2
const MEETING_PRIORITY_HOT_SPRINGS = 1

module.exports = {
    MEETING_PRIORITY_LOCK,
    MEETING_PRIORITY_JAIL,
    MEETING_PRIORITY_SEANCE,
    MEETING_PRIORITY_BANQUET,
    MEETING_DEAD_PARTY,
    MEETING_PRIORITY_HOT_SPRINGS,
}