// PRIORITY IS RESOLVED FROM LOWEST NUMBER (-101) TO HIGHEST NUMBER (100)

// VILLAGE CORE
export const PRIORITY_VILLAGE_MEETING = 0

// WINCHECK PRIORITY
const PRIORITY_WIN_CHECK_DEFAULT = 0
export const PRIORITY_WIN_IF_LYNCHED = -10
export const PRIORITY_GAME_WIN_CHECK = PRIORITY_WIN_CHECK_DEFAULT
export const PRIORITY_WIN_ALL_SAME_ROLE = PRIORITY_WIN_CHECK_DEFAULT
export const PRIORITY_WIN_AMONG_LAST_TWO = PRIORITY_WIN_CHECK_DEFAULT
export const PRIORITY_WIN_IF_ALIVE = PRIORITY_WIN_CHECK_DEFAULT
export const PRIORITY_WIN_WITH_MAFIA = PRIORITY_WIN_CHECK_DEFAULT
export const PRIORITY_WIN_WITH_MONSTERS = PRIORITY_WIN_CHECK_DEFAULT
export const PRIORITY_WIN_WITH_VILLAGE = PRIORITY_WIN_CHECK_DEFAULT

// NIGHT PRIORITY
export const PRIORITY_REDIRECT_ACTION_CONTROL = -101
export const PRIORITY_REDIRECT_ACTION_TARGET = -100
export const PRIORITY_STEAL_ACTIONS = -99
export const PRIORITY_SWAP_VISITORS_A = -98
export const PRIORITY_SWAP_VISITORS_B_AND_SWAP = -97
export const PRIORITY_NIGHT_ROLE_BLOCKER = -96
export const PRIORITY_CLEANSE_WEREWOLF_VISITORS = -95
export const PRIORITY_KILL_LYCAN_VISITORS_ENQUEUE = -95
export const PRIORITY_KILL_VISITORS_ENQUEUE = -95
export const PRIORITY_NIGHT_SAVER = -94

export const PRIORITY_BITING_WOLF = -50

const PRIORITY_MODIFY_INVESTIGATIVE_RESULT_DEFAULT = -50
export const PRIORITY_MAKE_INNOCENT = PRIORITY_MODIFY_INVESTIGATIVE_RESULT_DEFAULT
export const PRIORITY_REVEAL_TARGET_ON_DEATH = PRIORITY_MODIFY_INVESTIGATIVE_RESULT_DEFAULT

const PRIORITY_ITEM_GIVER_DEFAULT = -50
export const PRIORITY_ARMOR_GIVER = PRIORITY_ITEM_GIVER_DEFAULT
export const PRIORITY_GUN_GIVER = PRIORITY_ITEM_GIVER_DEFAULT

const PRIORITY_INVESTIGATIVE_DEFAULT = -10
export const PRIORITY_ALIGNMENT_LEARNER = PRIORITY_INVESTIGATIVE_DEFAULT
export const PRIORITY_ROLE_LEANER = PRIORITY_INVESTIGATIVE_DEFAULT

export const PRIORITY_CLEAN_DEATH = -2
export const PRIORITY_IDENTITY_STEALER = -2

const PRIORITY_KILL_DEFAULT = 0
export const PRIORITY_KILL_LYCAN_VISITORS = PRIORITY_KILL_DEFAULT
export const PRIORITY_KILL_VISITORS = PRIORITY_KILL_DEFAULT
export const PRIORITY_NIGHT_KILLER = PRIORITY_KILL_DEFAULT
export const PRIORITY_POISONER = PRIORITY_KILL_DEFAULT
export const PRIORITY_JAIL_EXECUTE = PRIORITY_KILL_DEFAULT

export const PRIORITY_MISMASON_MAFIA = 1

export const PRIORITY_BECOME_DEAD_ROLE = 50

const PRIORITY_INVESTIGATIVE_AFTER_RESOLVE_DEFAULT = 100
export const PRIORITY_TRACK = PRIORITY_INVESTIGATIVE_AFTER_RESOLVE_DEFAULT
export const PRIORITY_WATCH = PRIORITY_INVESTIGATIVE_AFTER_RESOLVE_DEFAULT

export const PRIORITY_MAKE_VISITORS_INSANE = 100

// MEETING PRIORITY
export const PRIORITY_JAIL_MEETING = -10
export const PRIORITY_CULT_MEETING = -2
export const PRIORITY_MASON_MEETING = -2
export const PRIORITY_MAFIA_MEETING = -1

// SUNSET PRIORITY
export const PRIORITY_LYNCH_REVENGE = 0
