// PRIORITY IS RESOLVED FROM LOWEST NUMBER (-200) TO HIGHEST NUMBER (50)

const PRIORITY_DOPPELGANGER = -200

const PRIORITY_MASON_WEREWOLF_REVEAL = -100

const PRIORITY_SEER = -50

const PRIORITY_ROBBER = -25

const PRIORITY_TROUBLEMAKER = -1

const PRIORITY_DRUNK = 25

const PRIORITY_INSOMNIAC = 50

module.exports = {
    
    PRIORITY_DOPPELGANGER,

    PRIORITY_MASON_WEREWOLF_REVEAL,

    PRIORITY_SEER,

    PRIORITY_ROBBER,

    PRIORITY_TROUBLEMAKER,

    PRIORITY_DRUNK,

    PRIORITY_INSOMNIAC

}